name: CI-pipeline
on:
  push:
    branches:
      - "*"
    tags:
      - "*"
     
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}


jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Print env
        run: env

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GIT_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  notify:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Send telegram message on push
        if: github.ref == 'refs/heads/dev' || 'refs/heads/master' || 'refs/heads/main' || 'refs/heads/testnet-v2' || 'refs/tags/v'
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ${{ github.actor }} created commit:
            Branch: ${{ github.ref_name }}
            Commit message: ${{ github.event.commits[0].message }}
            
            Repository: ${{ github.repository }}
            
            See changes: https://github.com/${{ github.repository }}/commit/${{ github.sha }}

  dispatch:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        if: github.ref == 'refs/heads/dev' || 'refs/heads/dev2' || 'refs/heads/qa' || 'refs/heads/master' || 'refs/heads/main' || 'refs/heads/testnet-v2'
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.GIT_TOKEN }}
          repository: ${{ github.repository }}
          event-type: triger
          client-payload: '{"ref": "${{ github.ref }}", "branch": "${{ github.ref_name }}", "sha": "${{ github.sha }}", "actor": "${{ github.actor }}", "comment": "${{ github.event.commits[0].message }}"}'
